// Package moh holds the audio this server plays to a party who cannot hear
// the other side (SPEC §4.4 rule 8b).
//
// Three clips, because there are three things to say: Music while someone
// holds you, Ringback while you are being transferred to a phone that is
// ringing, and Busy when that transfer failed and there is nobody left.
//
// It is pre-encoded, one file per codec a leg can be held on, because this
// server has no codecs and is not getting any: it is a copy relay, built
// with CGO_ENABLED=0 and the standard library alone. Playing hold music is
// therefore not "encode some audio" but "put these bytes on the wire",
// which is the same thing the relay already does with a caller's packets —
// same SSRC, same sequence space, same SRTP context, same payload type.
// Nothing is renegotiated and the held party is told nothing; its call
// simply carries on, which is why this works with any far end.
//
// The files are generated by tools/gen_moh.py (which needs ffmpeg); the
// audio is generated rather than sampled, so there is no licence and no
// attribution to carry (SPEC §8). Regenerate with:
//
//	python3 tools/gen_moh.py
package moh

import (
	"embed"
	"encoding/binary"
	"fmt"
	"strings"
)

//go:embed *.bin
var files embed.FS

// One 20 ms payload per entry, in playing order; the caller loops.
type Frames [][]byte

// The codec names diago uses (media.Codec.Name), lowercased.
var codecs = []string{"pcmu", "pcma", "g722", "opus"}

// clips are keyed "<clip>-<codec>".
var clips = map[string]Frames{}

func init() {
	for _, clip := range []string{"music", "ringback", "busy"} {
		for _, codec := range codecs {
			name := clip + "-" + codec + ".bin"
			f, err := load(name)
			if err != nil {
				// Embedded at build time, so this cannot be a deployment
				// problem — only a corrupt or truncated commit.
				panic(fmt.Sprintf("moh: %s: %v", name, err))
			}
			clips[clip+"-"+codec] = f
		}
	}
}

func load(name string) (Frames, error) {
	b, err := files.ReadFile(name)
	if err != nil {
		return nil, err
	}
	var out Frames
	for i := 0; i+2 <= len(b); {
		n := int(binary.BigEndian.Uint16(b[i:]))
		i += 2
		if i+n > len(b) {
			return nil, fmt.Errorf("frame %d runs past the end of the file", len(out))
		}
		out = append(out, b[i:i+n])
		i += n
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("no frames")
	}
	return out, nil
}

// Music is what a party hears while the other side holds them.
func Music(codec string) Frames { return Clip("music", codec) }

// Ringback is what a party being transferred hears while the target rings.
func Ringback(codec string) Frames { return Clip("ringback", codec) }

// Busy is what they hear when that transfer failed and the party who asked
// for it has already been released — there is nobody to go back to.
func Busy(codec string) Frames { return Clip("busy", codec) }

// Clip picks by name — "music", "ringback" or "busy". Nil for a codec we
// never pre-encoded, in which case the party gets the silence they would
// have had anyway.
func Clip(name, codec string) Frames {
	return clips[name+"-"+strings.ToLower(codec)]
}

// Seconds is how long the loop runs before it repeats.
func (f Frames) Seconds() float64 { return float64(len(f)) * 0.02 }
